spring:
  application:
      name: roundrobin


round:
  apis:
    instances: ["localhost:8081" , "localhost:8082" ,"localhost:8083" ]
    baseUrl: "http://"
    simpleApiUrl: "/api/v1/game"
    simpleApiPing: "/api/v1/ping"
    thresholdLatency: 500
    sleepTime: 0


server:
  port: 8090
